sudo:
 - required

language:
 - go
 - tip

script:
  - go get -v github.com/nguoianphu/go-smtp-server/smtp
  - env GOOS=windows GOARCH=amd64 go get -v github.com/nguoianphu/go-smtp-server/smtp
  - ls -la
  - go test -v github.com/nguoianphu/go-smtp-server
  - ./go-smtp-server
  
