sudo: required

language: go

install: go get

script:
  - go build -x go-smtp-server.go
  - ls
  - ./go-smtp-server
  # - diff -u <(echo -n) <(gofmt -d -s .)
  - go test -v github.com/nguoianphu/go-smtp-server
  
